from typing import Any

class Representer:
    def represent_dict(self, data: Any) -> Any: ...
    def represent_list(self, data: Any) -> Any: ...
    def represent_str(self, data: Any) -> Any: ...
    def add_representer(self, data: Any, fn: Any) -> Any: ...
